active: dev
dev:
  db:
    url: jdbc:mysql://127.0.0.1:3306/test_groovy
    user: root
    password: 123123
stable:
  db:
    url: jdbc:mysql://127.0.0.1:3306/test_groovy
    user: root
    passowrd: 123123